;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; Find the sum of all the even-valued terms in the sequence which do not exceed four million.

(ns c42.euler (:use clojure.test))

(defn backward-get
	[vector index]
	(get vector (- (count vector) index 1)))

(defn fibonacci
	[fib n]
	(if
			(> (first fib) n) (rest fib)
			(recur  
						 (vec (cons (+ (fib 0) (fib 1)) fib))
						 n)))

(def fibonacci-upto 
	(partial fibonacci [2 1]))

(defn sum-of-even-fibonacci-terms-upto
	[n]
	(reduce + (filter even? (fibonacci-upto n))))

(testing "Sum of even fibbonacci terms"
	(is (= 44 (sum-of-even-fibonacci-terms-upto 50)))
	(is (= 4613732 (sum-of-even-fibonacci-terms-upto 4000000))))

(testing "Fibonacci"
	(is (= '(8 5 3 2 1 1 0) (fibonacci [1 0] 10))))

(testing "Extracting the last n digits"
	(is (= 6 (backward-get [0 1 2 3 4 5 6] 0)))
	(is (= 5 (backward-get [0 1 2 3 4 5 6] 1)))
	(is (= 1 (backward-get [0 1 2 3 4 5 6] 5))))